### ISSUE TITLE
"Sample Office Data" button does not load new data

### ISSUE THREAD

**Issue by JamesDevJim** [JamesDevJim/james-energy-charts#3]
Would like "Sample Office Data" button to load data data from the following link when clicked.

https://buildingenergytools.com/wp-content/uploads/2021/05/FullSample.csv 

![image](https://user-images.githubusercontent.com/44040405/117870529-13d8c300-b251-11eb-8a66-e5a8af7462ff.png)

**Comment by seanwessmith** [comment]
implemented in commit bc2972ecae12810d03f588d780bb906d97526eba
